### ISSUE TITLE
Project Tutorial Proposal - Klaus

### ISSUE THREAD

**Issue by KlausMikhaelson** [codedex-io/projects#82]
1. Wreste with shapes(web based local multiplayer game using ThreeJs in react) - Medium
2. Winter Find(web based game using ThreeJs in react) - Medium
3. Shark Tanks(web based online multiplayer game using ThreeJs) - Hard
4. Virtual Room(watch youtube videos on sync in a webapp) - Medium

**Comment by Dusch4593** [comment]
Hey @KlausMikhaelson! This is Brandon from Codédex.

After considering your project ideas and sharing with my colleagues, we concluded that they wouldn't quite fit with our existing projects.

We're looking for project ideas that (a) utilize the core mechanics of the language(s) involved, and/or (b) feature not too many external, third-party packages or libraries.

More specific to your proposals, it seems that most of them utilize many JavaScript libraries (one uses Three.js and Express.js and SocketIO, for example -- too many libraries).

Another project, Winter-Find, uses TypeScript. I'm hesitant to include a TypeScript-based project at this time just because we haven't released our JavaScript course yet.
